# Ejercicio 01 - Catálogo de productos como lista

In [1]:
catalogo = ["Auriculares BT", 59.90,"Smartwatch S2", 149.00,"Tablet 10", 219.00,"Cargador USB-C", 18.50,"Cafetera Expres", 189.00,"Robot Aspirador", 279.00]

print("Elementos totales:", len(catalogo))
print("Productos:", len(catalogo) / 2)

nombres = catalogo[::2]
precios = catalogo[1::2]
print("Nombres:", nombres)
print("Precios:", precios)

posicion = catalogo.index("Robot Aspirador")
precio_robot = catalogo[posicion + 1]
print("Precio robot:", precio_robot)

ultimos_tres = catalogo[-6::2]
print("Últimos tres nombres:", ultimos_tres)

precio_medio = round(sum(precios) / len(precios), 2)
print("Media de precios:", precio_medio)

Elementos totales: 12
Productos: 6.0
Nombres: ['Auriculares BT', 'Smartwatch S2', 'Tablet 10', 'Cargador USB-C', 'Cafetera Expres', 'Robot Aspirador']
Precios: [59.9, 149.0, 219.0, 18.5, 189.0, 279.0]
Precio robot: 279.0
Últimos tres nombres: ['Cargador USB-C', 'Cafetera Expres', 'Robot Aspirador']
Media de precios: 152.4


# Ejercicio 02 - Inventario multialmacén con listas anidadas

In [2]:
inventario = [ ["ALM-NORTE", "Robot Aspirador", 34, 201.50],["ALM-NORTE", "Monitor 27", 58, 142.00],["ALM-SUR",   "Silla Ergonomica", 12, 178.90],["ALM-SUR",   "Robot Aspirador", 7, 201.50],["ALM-ESTE",  "Cafetera Expres", 41, 131.20],["ALM-ESTE",  "Monitor 27", 25, 142.00]]

print(inventario[3][1])

valor_stock = []

for fila in inventario:
    producto = fila[1]
    unidades = fila[2]
    precio = fila[3]
    valor = round(unidades * precio, 2)
    valor_stock.append([producto, valor])

print(valor_stock)

valor_total = 0
for fila in valor_stock:
    valor_total = valor_total + fila[1]

print("Valor total:", round(valor_total, 2))

alm_sur = inventario[2:4]

Robot Aspirador
[['Robot Aspirador', 6851.0], ['Monitor 27', 8236.0], ['Silla Ergonomica', 2146.8], ['Robot Aspirador', 1410.5], ['Cafetera Expres', 5379.2], ['Monitor 27', 3550.0]]
Valor total: 27573.5


Si dos almacenes dejan de estar contiguos, el slicing puede incluir filas de otro almacén o dejar fuera filas que pertenecen al almacén que queremos buscar.  
Por eso el slicing depende de la posición de las filas y no es una estrategia robusta para filtrar datos.

# Ejercicio 03 - Manipulación destructiva y copias de listas

In [3]:
precios_originales = [59.90, 149.00, 219.00, 18.50, 189.00, 279.00]

precios_rebajados = list(precios_originales)
precios_rebajados[0] = 49.90
print("Precios rebajados:", precios_rebajados)
print("Precios originales:", precios_originales)

precios_originales[0] = 59.90
copia_lista = list(precios_originales)
copia_slicing = precios_originales[:]
copia_lista[0] = 100.00
copia_slicing[0] = 67.67
print("Original:", precios_originales)
print("Copia 1:", copia_lista)
print("Copia 2:", copia_slicing)

precios_rebajados = list(precios_originales)
for i in range(len(precios_rebajados)):
    precios_rebajados[i] = round(precios_rebajados[i] * 0.90, 2)
print("Lista rebajada:", precios_rebajados)

precios_rebajados.extend([100,200])
precios_rebajados.insert(2, 79.90)
print("Lista actualizada:", precios_rebajados)

del precios_rebajados[4]
descartado = precios_rebajados.pop()

print("ID original:", id(precios_originales))
print("ID copia con lista:", id(copia_lista))
print("ID copia con slicing:", id(copia_slicing))
print("ID precios rebajados:", id(precios_rebajados))

Precios rebajados: [49.9, 149.0, 219.0, 18.5, 189.0, 279.0]
Precios originales: [59.9, 149.0, 219.0, 18.5, 189.0, 279.0]
Original: [59.9, 149.0, 219.0, 18.5, 189.0, 279.0]
Copia 1: [100.0, 149.0, 219.0, 18.5, 189.0, 279.0]
Copia 2: [67.67, 149.0, 219.0, 18.5, 189.0, 279.0]
Lista rebajada: [53.91, 134.1, 197.1, 16.65, 170.1, 251.1]
Lista actualizada: [53.91, 134.1, 79.9, 197.1, 16.65, 170.1, 251.1, 100, 200]
ID original: 1908834639488
ID copia con lista: 1908834682240
ID copia con slicing: 1908834644352
ID precios rebajados: 1908834682304


# Ejercicio 04 - Cola de pedidos pendientes

In [4]:
cola = ["PED-10021", "PED-10007", "PED-10044", "PED-10012", "PED-10033", "PED-10008"]

cola_invertida = cola[::-1]

cola_alfabetica = sorted(cola)

cola.sort(reverse=True)

atendidos = []
atendidos.append(cola.pop(0))
atendidos.append(cola.pop(0))

cola.insert(0, "PED-99999")

num_atendidos = len(atendidos)
num_pendientes = len(cola)
total_pedidos = num_atendidos + num_pendientes
porcentaje_avance = round((num_atendidos / total_pedidos) * 100, 1)

print(f"Atendidos: {num_atendidos}")
print(f"Pendientes: {num_pendientes}")
print(f"Avance: {porcentaje_avance} %")

Atendidos: 2
Pendientes: 5
Avance: 28.6 %


# Ejercicio 05 - Funciones propias para el cálculo de importes

In [5]:

def calcular_importe(unidades, precio_unitario, descuento_pct=0):
    bruto = unidades * precio_unitario
    neto = bruto * (1 - (descuento_pct / 100))
    return round(neto, 2)

def resumen_pedido(unidades, precio_unitario, descuento_pct=0):
    bruto = unidades * precio_unitario
    ahorro = bruto * (descuento_pct / 100)
    neto = bruto - ahorro
    return (round(bruto, 2), round(ahorro, 2), round(neto, 2))

help(calcular_importe)

bruto, ahorro, neto = resumen_pedido(unidades=3, precio_unitario=59.90, descuento_pct=10)
print("Bruto:", bruto, "€    Ahorro:", ahorro, "€    Neto:", neto, "€")

pedidos = [(3, 59.90, 10),(1, 279.00, 0),(5, 18.50, 20),(2, 149.00, 5),(4, 89.90, 15)]

importes = []
for ped in pedidos:
    importe_calculado = calcular_importe(ped[0], ped[1], ped[2])
    importes.append(importe_calculado)

print("\nLista de importes :", importes)
print("Número de pedidos :", len(importes))
print("Importe máximo    :", max(importes), "€")
print("Importe mínimo    :", min(importes), "€")
print("Importes ordenados:", sorted(importes))

Help on function calcular_importe in module __main__:

calcular_importe(unidades, precio_unitario, descuento_pct=0)

Bruto: 179.7 €    Ahorro: 17.97 €    Neto: 161.73 €

Lista de importes : [161.73, 279.0, 74.0, 283.1, 305.66]
Número de pedidos : 5
Importe máximo    : 305.66 €
Importe mínimo    : 74.0 €
Importes ordenados: [74.0, 161.73, 279.0, 283.1, 305.66]


# Ejercicio 06 — Normalización de códigos SKU con métodos

In [6]:
skus_crudos = ["  elc-0012-es ", "HOG-0045-ES", "dep-0003-pt  ","ofi-0021-es", "  ELC-0012-ES", "hog-0099-fr "]

skus_limpios = []
for sku in skus_crudos:
    skus_limpios.append(sku.strip().upper())

conteo_elc = skus_limpios.count("ELC-0012-ES")

pos_ofi = skus_limpios.index("OFI-0021-ES")

skus_separados = []
for sku in skus_limpios:
    skus_separados.append(sku.split("-"))
print(skus_separados)


skus_españa = []
for sku in skus_limpios:
    if sku.endswith("ES"):
        skus_españa.append(sku.replace("-", "."))
print(skus_españa)


cadena_unica = " | ".join(skus_españa)
print(cadena_unica)

[['ELC', '0012', 'ES'], ['HOG', '0045', 'ES'], ['DEP', '0003', 'PT'], ['OFI', '0021', 'ES'], ['ELC', '0012', 'ES'], ['HOG', '0099', 'FR']]
['ELC.0012.ES', 'HOG.0045.ES', 'OFI.0021.ES', 'ELC.0012.ES']
ELC.0012.ES | HOG.0045.ES | OFI.0021.ES | ELC.0012.ES


# Ejercicio 07 - Paquetes, importaciones y módulo propio

In [7]:
import math
from math import pi, ceil
import numpy as np
import pandas as pd
import random
import sys
sys.path.append("../src")
from utilidades import calcular_importe, clasificar_ticket


print("Raiz cudarada de 2809:", math.sqrt(2809))

print("Palets:", ceil(1375 / 24))

print("Versión de NumPy:", np.__version__)
print("Versión de Pandas:", pd.__version__)

random.seed(42)
valoraciones = [random.randint(1, 5) for _ in range(10)]
print(valoraciones)
print("Poner la semiñña hace que los dos empecemos el cálculo desde el mismo punto, por lo que random genera exactamente la misma secuencia de números")

print(calcular_importe(4, 89.90, 15))
print(clasificar_ticket(305.66))

Raiz cudarada de 2809: 53.0
Palets: 58
Versión de NumPy: 2.5.3
Versión de Pandas: 3.0.5
[1, 1, 3, 2, 2, 2, 1, 5, 1, 5]
Poner la semiñña hace que los dos empecemos el cálculo desde el mismo punto, por lo que random genera exactamente la misma secuencia de números
305.66
Medio


# Ejercicio 08 — Del cálculo con listas al cálculo vectorizado

In [8]:
import numpy as np

unidades = [3, 1, 5, 2, 4, 6, 2, 8, 3, 1]
precios  = [59.90, 279.00, 18.50, 149.00, 89.90, 27.50, 219.00, 14.90, 64.00, 239.00]

try:
    fallo = unidades * precios
except Exception as e:
    print(type(e).__name__, "-", e)

np_unidades = np.array(unidades)
np_precios = np.array(precios)
print(np_unidades.shape, "|", np_unidades.dtype)
print(np_precios.shape, "|", np_precios.dtype)

importes = np_unidades * np_precios
print(importes)
print(importes.sum(), "€")

importes_recargo = importes * 1.04

print("aqui")
mixto = np.array([1, "dos", 3.0, True])
print(mixto.dtype)

print("Tiempo python:")
resultado = []
for u, p in zip(unidades, precios):
    resultado.append(u * p)
%timeit resultado

print("Tiempo numpy:")
%timeit np_unidades * np_precios

TypeError - can't multiply sequence by non-int of type 'list'
(10,) | int64
(10,) | float64
[179.7 279.   92.5 298.  359.6 165.  438.  119.2 192.  239. ]
2362.0 €
aqui
<U32
Tiempo python:
11.8 ns ± 0.31 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
Tiempo numpy:
1.2 μs ± 26.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Ejercicio 09 - Subsetting con máscaras booleanas

In [9]:
import numpy as np

unidades = [3, 1, 5, 2, 4, 6, 2, 8, 3, 1]
precios  = [59.90, 279.00, 18.50, 149.00, 89.90, 27.50, 219.00, 14.90, 64.00, 239.00]
np_unidades = np.array(unidades)
np_precios = np.array(precios)
importes = np_unidades * np_precios

caros = np_precios > 100
print(caros)

precios_caros = np_precios[caros]
print(precios_caros)

cantidad_caros = caros.sum()
print(cantidad_caros)

importes_caros = importes[caros]
suma_importes_caros = importes_caros.sum()
print(importes_caros)
print(suma_importes_caros, "€")

posiciones_caros = np.where(caros)
print(posiciones_caros[0])

varias = np_unidades >= 2
seleccion = (np_precios > 100) & (np_unidades >= 2)

print(importes[seleccion])

[False  True False  True False False  True False False  True]
[279. 149. 219. 239.]
4
[279. 298. 438. 239.]
1254.0 €
[1 3 6 9]
[298. 438.]


# Ejercicio 10 - Matriz de ventas por trimestre y región

In [10]:
import numpy as np

ventas_2d = np.array([
    [15200.50, 11800.25, 12950.00,  9870.40, 13400.10], # T1
    [16840.75, 12310.60, 13480.90, 11020.35, 14100.80], # T2
    [12535.72, 10663.06, 11221.59, 12673.08, 12334.38], # T3
])

print(ventas_2d.shape)
print(ventas_2d.ndim)
print(ventas_2d.size)

fila_t2 = ventas_2d[1, :]
col_centro = ventas_2d[:, 4]
print(fila_t2)
print(col_centro)


valor_t3_este = ventas_2d[2, 2]
print(valor_t3_este, "€")

submatriz = ventas_2d[0:2, 0:3]
print(submatriz)

totales_trimestre = np.sum(ventas_2d, axis=1)
totales_region = np.sum(ventas_2d, axis=0)
print(totales_trimestre)
print(totales_region)

t4_prevision = ventas_2d[2, :] * 1.06
ventas_con_t4 = np.vstack((ventas_2d, t4_prevision))
print(ventas_con_t4.round(2))

nombres_regiones = ["Norte", "Sur", "Este", "Oeste", "Centro"]
indice_max = np.argmax(totales_region)
mejor_region = nombres_regiones[indice_max]
print(mejor_region)

(3, 5)
2
15
[16840.75 12310.6  13480.9  11020.35 14100.8 ]
[13400.1  14100.8  12334.38]
11221.59 €
[[15200.5  11800.25 12950.  ]
 [16840.75 12310.6  13480.9 ]]
[63221.25 67753.4  59427.83]
[44576.97 34773.91 37652.49 33563.83 39835.28]
[[15200.5  11800.25 12950.    9870.4  13400.1 ]
 [16840.75 12310.6  13480.9  11020.35 14100.8 ]
 [12535.72 10663.06 11221.59 12673.08 12334.38]
 [13287.86 11302.84 11894.89 13433.46 13074.44]]
Norte


# Ejercicio 11 - Estadística descriptiva sobre telemetría simulada

In [11]:
import numpy as np

rng = np.random.default_rng(2024)
temperatura = rng.normal(68, 6.5, 500)
vibracion = np.abs(rng.normal(2.4, 0.8, 500))

media_temp = np.mean(temperatura)
mediana_temp = np.median(temperatura)
std_temp = np.std(temperatura)

print(f"Media  : {media_temp:.2f}")
print(f"Mediana: {mediana_temp:.2f}")
print(f"Desv   : {std_temp:.2f} | Min: {np.min(temperatura):.2f} | Max: {np.max(temperatura):.2f}")


percentiles_vib = np.percentile(vibracion, [25, 50, 75, 95])
print("\n3. Percentiles de vibración (25, 50, 75, 95):")
print("  ", np.round(percentiles_vib, 2))

matriz_telemetria = np.column_stack((temperatura, vibracion))
print(matriz_telemetria.shape)

matriz_corr = np.corrcoef(temperatura, vibracion)
print(np.round(matriz_corr, 3))

umbral = media_temp + (2 * std_temp)
superan_umbral = np.sum(temperatura > umbral)
porcentaje = (superan_umbral / len(temperatura)) * 100

print(f"\n6. Umbral calculado (Media + 2*Std): {umbral:.2f} °C")
print(f"   Lecturas que lo superan: {superan_umbral} ({porcentaje:.1f}%)")

Media  : 68.03
Mediana: 68.13
Desv   : 6.50 | Min: 49.01 | Max: 88.29

3. Percentiles de vibración (25, 50, 75, 95):
   [1.89 2.39 2.92 3.73]
(500, 2)
[[1.    0.007]
 [0.007 1.   ]]

6. Umbral calculado (Media + 2*Std): 81.04 °C
   Lecturas que lo superan: 11 (2.2%)


# Ejercicio 12 - Diccionarios simples y anidados

In [12]:
tarifas_envio = {
    "Norte": 4.95, 
    "Sur": 5.50, 
    "Este": 5.20, 
    "Oeste": 6.10, 
    "Centro": 3.90
}

print(tarifas_envio["Este"], "€")

tarifas_envio["Insular"] = 9.80
tarifas_envio["Oeste"] = 5.95
del tarifas_envio["Sur"]
comprobacion_sur = "Sur" in tarifas_envio
print(comprobacion_sur)

for region, tarifa in tarifas_envio.items():
    print(f"   {region} -> {tarifa} €")

red_logistica = {
    "Norte":  {"almacen": "ALM-NORTE", "tarifa": 4.95, "entrega_h": 24},
    "Este":   {"almacen": "ALM-ESTE",  "tarifa": 5.20, "entrega_h": 48},
    "Centro": {"almacen": "ALM-CENTRO","tarifa": 3.90, "entrega_h": 24},
}

tiempo_este = red_logistica["Este"]["entrega_h"]
print(tiempo_este, "")

red_logistica["Oeste"] = {"almacen": "ALM-OESTE", "tarifa": 5.95, "entrega_h": 72}

for region, datos in red_logistica.items():
    print(f"   [{region}] Almacén: {datos['almacen']} | Tarifa: {datos['tarifa']} € | Entrega: {datos['entrega_h']}h")

5.2 €
False
   Norte -> 4.95 €
   Este -> 5.2 €
   Oeste -> 5.95 €
   Centro -> 3.9 €
   Insular -> 9.8 €
48 
   [Norte] Almacén: ALM-NORTE | Tarifa: 4.95 € | Entrega: 24h
   [Este] Almacén: ALM-ESTE | Tarifa: 5.2 € | Entrega: 48h
   [Centro] Almacén: ALM-CENTRO | Tarifa: 3.9 € | Entrega: 24h
   [Oeste] Almacén: ALM-OESTE | Tarifa: 5.95 € | Entrega: 72h


# Ejercicio 13 - Paquetes, importaciones y módulo propio

In [13]:
import pandas as pd

almacenes_dict = {
    "codigo":    ["ALM-NORTE", "ALM-SUR", "ALM-ESTE", "ALM-OESTE", "ALM-CENTRO"],
    "ciudad":    ["Bilbao", "Sevilla", "Valencia", "Vigo", "Madrid"],
    "m2":        [4200, 3100, 3800, 2600, 6500],
    "operarios": [48, 31, 39, 22, 74],
}
almacenes = pd.DataFrame(almacenes_dict)

print(almacenes)

almacenes = almacenes.set_index("codigo")
print(almacenes)

ventas = pd.read_csv("../data/ventas_retail.csv")
empleados = pd.read_csv("../data/empleados.csv", index_col="id_empleado")
sensores = pd.read_csv("../data/sensores_planta.csv")

print(ventas.head(8))
print(ventas.tail(3))
print(ventas.shape)

ventas.info()

print("Valores nulos:", ventas.isna().sum())

print(ventas.shape)
print(empleados.shape)
print(sensores.shape)

       codigo    ciudad    m2  operarios
0   ALM-NORTE    Bilbao  4200         48
1     ALM-SUR   Sevilla  3100         31
2    ALM-ESTE  Valencia  3800         39
3   ALM-OESTE      Vigo  2600         22
4  ALM-CENTRO    Madrid  6500         74
              ciudad    m2  operarios
codigo                               
ALM-NORTE     Bilbao  4200         48
ALM-SUR      Sevilla  3100         31
ALM-ESTE    Valencia  3800         39
ALM-OESTE       Vigo  2600         22
ALM-CENTRO    Madrid  6500         74
   id_pedido       fecha  region    categoria          producto  unidades  \
0  PED-10153  2025-01-01  Centro  Electronica        Tablet 10"         2   
1  PED-10030  2025-01-02     Sur      Deporte   Zapatilla Trail         4   
2  PED-10343  2025-01-02   Oeste      Oficina  Teclado Mecanico         3   
3  PED-10298  2025-01-02   Oeste        Hogar   Robot Aspirador         6   
4  PED-10144  2025-01-03     Sur      Deporte       Mochila 30L         5   
5  PED-10225  2025-01-03  

# Ejercicio 14 — Selección con corchetes, loc e iloc

In [14]:
import pandas as pd

empleados = pd.read_csv("../data/empleados.csv", index_col="id_empleado")
print(type(empleados["salario_base"]))
print(type((empleados[["salario_base"]])))

print((empleados[["departamento","ciudad","salario_base"]]))
print(empleados[9:15])

print(empleados.loc[["EMP-1042"]])
print(empleados.loc[["EMP-1005","EMP-1020","EMP-1099"],["departamento","modalidad"]])
print(empleados.iloc[:3,[2,5]])

print(empleados.loc[:,["nombre","bonus_pct"]])

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
            departamento     ciudad  salario_base
id_empleado                                      
EMP-1001      Ingenieria   Valencia         43297
EMP-1002         Soporte   Valencia         32554
EMP-1003     Operaciones   Valencia         47738
EMP-1004          Ventas  Barcelona         39733
EMP-1005        Finanzas     Madrid         44990
...                  ...        ...           ...
EMP-1176          Ventas    Sevilla         37301
EMP-1177          Ventas  Barcelona         44604
EMP-1178        Finanzas     Bilbao         46786
EMP-1179         Soporte     Madrid         35736
EMP-1180      Ingenieria     Madrid         46315

[180 rows x 3 columns]
                    nombre departamento     ciudad  antiguedad_anios  \
id_empleado                                                            
EMP-1010      Victor Nieto     Finanzas   Valencia                16   
EMP-1011      Ainhoa Rojas      Soporte  Barcelona         

# Ejercicio 15 - Columnas calculadas, agregación y exportación

In [15]:
ventas["importe_bruto"] = ventas["unidades"] * ventas["precio_unitario"]

ventas["importe_neto"] = round(ventas["importe_bruto"] * (1 - ventas["descuento_pct"] / 100), 2)

ventas["ticket_medio"] = ventas["importe_neto"] / ventas["unidades"]

facturacion_region = ventas.groupby("region")["importe_neto"].sum().sort_values(ascending=False)
print(facturacion_region)

agrupacion_categoria_canal = ventas.groupby(["categoria", "canal"]).agg({
    "importe_neto": "mean",
    "unidades": "sum"
})

top_productos = ventas.groupby("producto")["importe_neto"].sum().nlargest(5)
print(top_productos)


mediana_satisfaccion = ventas["satisfaccion"].median()
ventas["satisfaccion"] = ventas["satisfaccion"].fillna(mediana_satisfaccion)
ventas["canal"] = ventas["canal"].fillna("Desconocido")

facturacion_region.to_csv("../outputs/facturacion_por_region.csv")

region
Norte     44576.98
Centro    39835.28
Este      37652.49
Sur       34773.90
Oeste     33563.82
Name: importe_neto, dtype: float64
producto
Robot Aspirador     32322.15
Tablet 10"          24068.10
Silla Ergonomica    22394.30
Smartwatch S2       20316.15
Cafetera Expres     19778.85
Name: importe_neto, dtype: float64


# Ejercicio 16 — Operadores de comparación y booleanos

In [16]:
import numpy as np

print(2 < 3)
print("Norte" == "norte")
print(True + True + False)
print(3 != 3.0)
print("Zapatilla" > "Mochila")

unidades = 6
precio = 149.0
descuento = 15

condicion_and = (unidades > 4) and (descuento >= 10)
print(condicion_and)

condicion_or = (precio < 50) or (precio > 200)
print(condicion_or)

negacion_and = not condicion_and
print(negacion_and)

temp = np.array([64.2, 88.1, 71.0, 92.5, 69.8])
vib = np.array([1.9, 3.4, 2.1, 4.0, 2.2])

try:
    fallo = temp > 70 and vib > 3
except ValueError as e:
    print(e)

solucion_1 = np.logical_and(temp > 70, vib > 3)
solucion_2 = (temp > 70) & (vib > 3)

print(solucion_1)
print(solucion_2)
print(np.array_equal(solucion_1, solucion_2))

True
False
2
False
True
True
False
False
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[False  True False  True False]
[False  True False  True False]
True


# Ejercicio 17 — if / elif / else aplicado a mantenimiento predictivo

In [17]:
import pandas as pd
def nivel_riesgo(temperatura):
    if temperatura > 85:
        return "CRÍTICO"
    elif temperatura > 76:
        return "ALTO"
    elif temperatura > 70:
        return "MEDIO"
    else:
        return "BAJO"

print(nivel_riesgo(92.5))
print(nivel_riesgo(80.0))
print(nivel_riesgo(72.3))
print(nivel_riesgo(64.1))

sensores = pd.read_csv("../data/sensores_planta.csv")
sensores["riesgo"] = sensores["temperatura_c"].apply(nivel_riesgo)
print(sensores[["id_maquina", "temperatura_c", "riesgo"]].head())

print(sensores["riesgo"].value_counts())
filtrado = sensores[sensores["riesgo"] == "CRÍTICO"]
print(filtrado["id_maquina"].value_counts())

CRÍTICO
ALTO
MEDIO
BAJO
  id_maquina  temperatura_c riesgo
0     MAQ-01          58.92   BAJO
1     MAQ-03          71.72  MEDIO
2     MAQ-02          67.93   BAJO
3     MAQ-03          73.10  MEDIO
4     MAQ-03          69.37   BAJO
riesgo
BAJO       347
MEDIO      161
ALTO        72
CRÍTICO     20
Name: count, dtype: int64
id_maquina
MAQ-04    6
MAQ-02    5
MAQ-01    5
MAQ-03    4
Name: count, dtype: int64


# Ejercicio 18 - Filtrado avanzado de DataFrames

In [18]:
online_500 = ventas[(ventas["canal"] == "Online") & (ventas["importe_neto"] > 500)]

norte_centro = ventas[ventas["region"].isin(["Norte", "Centro"])]

dto_10_20 = ventas[ventas["descuento_pct"].between(10, 20)]

electronica_volumen = ventas[
    (ventas["categoria"] == "Electronica") & 
    (ventas["unidades"] > 2) & 
    (ventas["descuento_pct"] != 0)
]

no_oficina = ventas[~(ventas["categoria"] == "Oficina")]

query_online_500 = ventas.query("canal == 'Online' and importe_neto > 500")

ingenieros_senior = empleados[
    (empleados["departamento"] == "Ingenieria") & 
    (empleados["modalidad"] == "Remoto") & 
    (empleados["antiguedad_anios"] > 5)
].sort_values(by="salario_base", ascending=False)

ingenieros_senior.to_csv("../outputs/ingenieria_remoto_senior.csv", header=True)

# Ejercicio 19 — Bucles sobre estructuras de datos

In [19]:
import numpy as np

regiones = ["Norte", "Sur", "Este", "Oeste", "Centro"]
inventario = [
    ["ALM-NORTE", "Robot Aspirador", 34, 201.50],
    ["ALM-NORTE", "Monitor 27", 58, 142.00],
    ["ALM-SUR",   "Silla Ergonomica", 12, 178.90],
    ["ALM-SUR",   "Robot Aspirador", 7, 201.50],
    ["ALM-ESTE",  "Cafetera Expres", 41, 131.20],
    ["ALM-ESTE",  "Monitor 27", 25, 142.00],
]
tarifas_envio = {"Norte": 4.95, "Este": 5.20, "Oeste": 5.95, "Centro": 3.90, "Insular": 9.80}
np_precios = np.array([59.90, 279.00, 18.50, 149.00, 89.90, 27.50, 219.00, 14.90, 64.00, 239.00])

stock = 12
lote = 0
while stock < 60:
    lote = lote + 1
    stock = stock + 8
    print("   Lote", lote, "-> stock:", stock)

for region in regiones:
    print("  ", region.upper())

for i, region in enumerate(regiones, start=1):
    print(f"   Región {i}: {region}")

for almacen, producto, unidades, coste in inventario:
    print(f"   {almacen} | {producto} | {round(unidades * coste, 2)} €")

for region, tarifa in tarifas_envio.items():
    print(f"   {region}: {tarifa} €")

for precio in np_precios:
    print("  ", round(precio * 1.04, 2), "€")

   Lote 1 -> stock: 20
   Lote 2 -> stock: 28
   Lote 3 -> stock: 36
   Lote 4 -> stock: 44
   Lote 5 -> stock: 52
   Lote 6 -> stock: 60
   NORTE
   SUR
   ESTE
   OESTE
   CENTRO
   Región 1: Norte
   Región 2: Sur
   Región 3: Este
   Región 4: Oeste
   Región 5: Centro
   ALM-NORTE | Robot Aspirador | 6851.0 €
   ALM-NORTE | Monitor 27 | 8236.0 €
   ALM-SUR | Silla Ergonomica | 2146.8 €
   ALM-SUR | Robot Aspirador | 1410.5 €
   ALM-ESTE | Cafetera Expres | 5379.2 €
   ALM-ESTE | Monitor 27 | 3550.0 €
   Norte: 4.95 €
   Este: 5.2 €
   Oeste: 5.95 €
   Centro: 3.9 €
   Insular: 9.8 €
   62.3 €
   290.16 €
   19.24 €
   154.96 €
   93.5 €
   28.6 €
   227.76 €
   15.5 €
   66.56 €
   248.56 €


# Ejercicio 20 — Iteración sobre DataFrames

In [26]:
from utilidades import clasificar_ticket

for etiqueta, fila in ventas.head(5).iterrows():
    print("   ", fila["region"], "|", fila["producto"], "|", fila["importe_neto"], "€")

ventas["codigo_region"] = ventas["region"].str[:3].str.upper()

ventas["segmento_ticket"] = ventas["importe_neto"].apply(clasificar_ticket)

print(ventas["segmento_ticket"].value_counts())

sensores["eficiencia"] = (sensores["unidades_producidas"] / sensores["temperatura_c"]).round(3)

resumen_por_region = {}

for region in ventas["region"].unique():
    filtrado = ventas[ventas["region"] == region]
    resumen_por_region[region] = round(filtrado["importe_neto"].sum(), 2)

print("------------------------------------------------------------------")
print(resumen_por_region)
print(ventas.groupby("region")["importe_neto"].sum().sort_values(ascending=False))


    Centro | Tablet 10" | 350.4 €
    Sur | Zapatilla Trail | 476.0 €
    Oeste | Teclado Mecanico | 242.73 €
    Oeste | Robot Aspirador | 1422.9 €
    Sur | Mochila 30L | 256.0 €
segmento_ticket
Alto     167
Medio    152
Bajo     101
Name: count, dtype: int64
------------------------------------------------------------------
{'Centro': np.float64(39835.28), 'Sur': np.float64(34773.9), 'Oeste': np.float64(33563.82), 'Norte': np.float64(44576.98), 'Este': np.float64(37652.49)}
region
Norte     44576.98
Centro    39835.28
Este      37652.49
Sur       34773.90
Oeste     33563.82
Name: importe_neto, dtype: float64
